"""
This type stub file was generated by pyright.
"""

from shapely.geometry.base import BaseMultipartGeometry

"""Multi-part collections of geometries
"""

class GeometryCollection(BaseMultipartGeometry):
    """A heterogeneous collection of geometries

    Attributes
    ----------
    geoms : sequence
        A sequence of Shapely geometry instances
    """

    def __init__(self, geoms=...) -> None:
        """
        Parameters
        ----------
        geoms : list
            A list of shapely geometry instances, which may be heterogeneous.

        Example
        -------
        Create a GeometryCollection with a Point and a LineString

          >>> from shapely.geometry import LineString, Point
          >>> p = Point(51, -1)
          >>> l = LineString([(52, -1), (49, 2)])
          >>> gc = GeometryCollection([p, l])
        """
        ...
    @property
    def __geo_interface__(self): ...
    @property
    def geoms(self): ...

def geos_geometrycollection_from_py(ob):  # -> tuple[Any, Literal[2, 3]]:
    """Creates a GEOS GeometryCollection from a list of geometries"""
    ...
