import warnings
from functools import wraps

import shapely.affinity
from shapely import coords
from shapely.geometry import linestring, polygon

def method_wrapper(f): ...

__all__ = ["available", "enable", "disable", "enabled"]
_orig = ...
enabled: bool = ...
available: bool = ...

def enable() -> None: ...
def disable() -> None: ...
