"""
This type stub file was generated by pyright.
"""

import os
import sys

"""
Minimal proxy to a GEOS C dynamic library, which is system dependent

Two environment variables influence this module: GEOS_LIBRARY_PATH and/or
GEOS_CONFIG.

If GEOS_LIBRARY_PATH is set to a path to a GEOS C shared library, this is
used. Otherwise GEOS_CONFIG can be set to a path to `geos-config`. If
`geos-config` is already on the PATH environment variable, then it will
be used to help better guess the name for the GEOS C dynamic library.
"""
log = ...
ch = ...
if "all" in sys.warnoptions: ...
lgeos = ...
if "GEOS_LIBRARY_PATH" in os.environ:
    geos_library_path = ...
if "GEOS_CONFIG" in os.environ:
    geos_config = ...
else:
    geos_config = ...

def get_geos_config(option):  # -> str:
    """Get configuration option from the `geos-config` development utility

    Path to utility is set with a module-level `geos_config` variable, which
    can be changed or unset.
    """
    ...

if notlgeos and geos_config:
    base = ...
    name = ...
    guesses = ...

def load_dll(libname, fallbacks=...): ...

if sys.platform.startswith("linux"):
    free = ...
else: ...
