class ShapelyError(Exception): ...
class UnsupportedGEOSVersionError(ShapelyError): ...
class ReadingError(ShapelyError): ...
class WKBReadingError(ReadingError): ...
class WKTReadingError(ReadingError): ...
class DimensionError(ShapelyError): ...
class TopologicalError(ShapelyError): ...
class PredicateError(ShapelyError): ...
class ShapelyDeprecationWarning(FutureWarning): ...
class EmptyPartError(ShapelyError): ...

class GeometryTypeError(ShapelyError, TypeError, ValueError):
    def __init__(self, msg) -> None: ...

class InvalidGeometryError(ShapelyError, TypeError, ValueError):
    def __init__(self, msg) -> None: ...
