"""
This type stub file was generated by pyright.
"""

from shapely.geos import lgeos

"""Implementation of the intermediary layer between Shapely and GEOS

This is layer number 2 from the list below.

1) geometric objects: the Python OO API.
2) implementation map: an abstraction that permits different backends.
3) backend: callable objects that take Shapely geometric objects as arguments
   and, with GEOS as a backend, translate them to C data structures.
4) GEOS library: algorithms implemented in C++.

Shapely 1.2 includes a GEOS backend and it is the default.
"""

class ImplementationError(AttributeError, KeyError, NotImplementedError):
    """To be raised when the registered implementation does not
    support the requested method."""

    ...

def delegated(func):  # -> (*args: Unknown, **kwargs: Unknown) -> Unknown:
    """A delegated method raises AttributeError in the absence of backend
    support."""
    ...

class BaseImpl:
    """Base class for registrable implementations."""

    def __init__(self, values) -> None: ...
    def update(self, values): ...
    def __getitem__(self, key): ...
    def __contains__(self, key): ...

class GEOSImpl(BaseImpl):
    """GEOS implementation"""

    def __repr__(self): ...

IMPL330 = ...
IMPL360 = ...

def impl_items(defs): ...

imp = ...
if lgeos.geos_version >= (3, 6, 0): ...
DefaultImplementation = ...
