"""
This type stub file was generated by pyright.
"""

from shapely.topology import Delegating

"""Linear referencing
"""

class LinearRefBase(Delegating): ...

class ProjectOp(LinearRefBase):
    def __call__(self, this, other): ...

class InterpolateOp(LinearRefBase):
    def __call__(self, this, distance): ...
