"""
This type stub file was generated by pyright.
"""

"""Load/dump geometries using the well-known binary (WKB) format.

Also provides pickle-like convenience functions.
"""

def loads(data, hex=...):  # -> BaseGeometry:
    """Load a geometry from a WKB byte string, or hex-encoded string if
    ``hex=True``.

    Raises
    ------
    WKBReadingError, UnicodeDecodeError
        If ``data`` contains an invalid geometry.
    """
    ...

def load(fp, hex=...):  # -> BaseGeometry:
    """Load a geometry from an open file.

    Raises
    ------
    WKBReadingError, UnicodeDecodeError
        If the given file contains an invalid geometry.
    """
    ...

def dumps(ob, hex=..., srid=..., **kw):  # -> str | bytes:
    """Dump a WKB representation of a geometry to a byte string, or a
    hex-encoded string if ``hex=True``.

    Parameters
    ----------
    ob : geometry
        The geometry to export to well-known binary (WKB) representation
    hex : bool
        If true, export the WKB as a hexadecimal string. The default is to
        return a binary string/bytes object.
    srid : int
        Spatial reference system ID to include in the output. The default value
        means no SRID is included.
    **kw : kwargs
        See available keyword output settings in ``shapely.geos.WKBWriter``.
    """
    ...

def dump(ob, fp, hex=..., **kw):  # -> None:
    """Dump a geometry to an open file."""
    ...
