from typing import Optional, Protocol

from shapely.geometry.base import BaseGeometry

class _Readable(Protocol):
    def read(self): ...

class _Writeable(Protocol):
    def write(self): ...

def loads(data: bytes | str, hex: bool = ...) -> BaseGeometry: ...
def load(fp: _Readable, hex: bool = ...): ...
def dumps(
    ob: BaseGeometry, hex: bool = ..., srid: Optional[int] = ..., **kw
) -> str | bytes: ...
def dump(ob: BaseGeometry, fp: _Writeable, hex: bool = ..., **kw): ...
