from shapely.geometry import Point, Polygon

class Cell:
    centroid: Point
    x: float
    y: float
    h: float
    distance: float
    max_distance: float

    def __init__(self, x: float, y: float, h: float, polygon: Polygon) -> None: ...
    def __lt__(self, other: Cell) -> bool: ...
    def __le__(self, other: Cell) -> bool: ...
    def __eq__(self, other: Cell) -> bool: ...
    def __ne__(self, other: Cell) -> bool: ...
    def __gt__(self, other: Cell) -> bool: ...
    def __ge__(self, other: Cell) -> bool: ...

def polylabel(polygon: Polygon, tolerance: float = ...) -> Point: ...
