"""
This type stub file was generated by pyright.
"""

from shapely import speedups

from ._vectorized import contains, touches

"""Provides multi-point element-wise operations such as ``contains``."""
